branches: 
  only: 
    - travis
language: c

os:
  - linux
#  - osx

sudo: required
dist: trusty
notifications: 
  email: false

  
git:
    submodules: false

services: 
  - docker

matrix:
  include:
    - os: osx
      script:
  
    - os: linux
      before_install: 
        - sudo apt-get update
        - sudo service docker restart
        - sleep 5
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - sudo docker pull onnc/ubuntu-14.04-llvm
        - sudo docker create --privileged=true -t --name container  onnc/ubuntu-14.04-llvm
        - sudo docker start container


      script: 
        - sudo docker exec -t container /bin/bash -c "sudo git clone https://github.com/ONNC/onnc-umbrella.git"
        - sudo docker exec -t container /bin/bash -c "cd onnc-umbrella && sudo git submodule init && sudo git submodule update"
        - sudo docker exec -t container /bin/bash -c "sudo mkdir ./onnc-umbrella/onnc-build"
        - sudo docker exec -t container /bin/bash -c "cd ./onnc-umbrella"
        - sudo docker exec -t container /bin/bash -c "./build.sh dbg ./onnc-build"
